import {BackgroundEntity} from '../../../common/src/api/document/entities/background-entity';
import {EntityType} from '../../../common/src/api/document/entities/types';

export const bg1: BackgroundEntity = {
    parentUid: null,
    type: EntityType.BACKGROUND_IMAGE,
    filename: 'bg.pdf',
    center: {x: 1, y: 2},
    crop: {x: -1, y: 2.4, w: 100, h: 101},
    offset: {x: 1, y: 2},
    page: 0,
    paperSize: {
        name: 'awwefew',
        widthMM: 12,
        heightMM: 200,
    },
    pointA: {x: -1, y: 2},
    pointB: {x: 3, y: 5},
    rotation: 12,
    scaleFactor: 1,
    scaleName: '1:200',
    totalPages: 100,
    uid: 'uid1',
    uri: 'awuhevgfyhwe',
};
export const bg2B: BackgroundEntity = {
    parentUid: null,
    type: EntityType.BACKGROUND_IMAGE,
    filename: 'bg.pdf',
    center: {x: 1, y: 2},
    crop: {x: -1, y: 2.5, w: 100, h: 101},
    offset: {x: 1, y: 2},
    page: 0,
    paperSize: {
        name: 'asdf',
        widthMM: 100,
        heightMM: 200,
    },
    pointA: {x: -1, y: 2},
    pointB: {x: 3, y: 4},
    rotation: 12,
    scaleFactor: 1,
    scaleName: '1:200',
    totalPages: 100,
    uid: 'uid2',
    uri: 'wefjnwkeifjw',
};
export const bg2: BackgroundEntity = {
    parentUid: null,
    type: EntityType.BACKGROUND_IMAGE,
    filename: 'bg.pdf',
    center: {x: 1, y: 2},
    crop: {x: -1, y: 2.5, w: 100, h: 101},
    offset: {x: 1, y: 2},
    page: 0,
    paperSize: {
        name: 'asdf',
        widthMM: 100,
        heightMM: 200,
    },
    pointA: {x: -1, y: 2},
    pointB: {x: 3, y: 4},
    rotation: 12,
    scaleFactor: 1,
    scaleName: '1:200',
    totalPages: 100,
    uid: 'uid2',
    uri: 'awuhevgfyhwe',
};
export const bg3: BackgroundEntity = {
    parentUid: null,
    type: EntityType.BACKGROUND_IMAGE,
    filename: 'bg.pdf',
    center: {x: 100, y: 2},
    crop: {x: -1, y: 2.5, w: 100, h: 101},
    offset: {x: 1, y: 4},
    page: 0,
    paperSize: {
        name: 'asdf',
        widthMM: 100,
        heightMM: 200,
    },
    pointA: {x: -1, y: 2},
    pointB: {x: 3, y: 4},
    rotation: 12,
    scaleFactor: 1,
    scaleName: '1:200',
    totalPages: 100,
    uid: 'uid3',
    uri: 'gerreger',
};



export const bg4: BackgroundEntity = {
    parentUid: null,
    type: EntityType.BACKGROUND_IMAGE,
    filename: 'bg.pdf',
    center: {x: 100, y: 2},
    crop: {x: -1, y: 2.5, w: 100, h: 101},
    offset: {x: 1, y: 4},
    page: 0,
    paperSize: {
        name: 'asdf',
        widthMM: 100,
        heightMM: 200,
    },
    pointA: {x: -1, y: 2},
    pointB: {x: 3, y: 4},
    rotation: 12,
    scaleFactor: 1,
    scaleName: '1:200',
    totalPages: 100,
    uid: 'uid4',
    uri: 'ewoikfkweo',
};

export const bg4B: BackgroundEntity = {
    parentUid: null,
    type: EntityType.BACKGROUND_IMAGE,
    filename: 'bg.pdf',
    center: {x: 100, y: 2},
    crop: {x: -1, y: 2.5, w: 10, h: 101},
    offset: {x: 1, y: 4},
    page: 0,
    paperSize: {
        name: 'asdf',
        widthMM: 100,
        heightMM: 200,
    },
    pointA: {x: -1, y: 2},
    pointB: {x: 3, y: 4},
    rotation: 12,
    scaleFactor: 1,
    scaleName: '1:200',
    totalPages: 100,
    uid: 'uid4',
    uri: 'fwkemfewpokfowe',
};

export const bg4C: BackgroundEntity = {
    parentUid: null,
    type: EntityType.BACKGROUND_IMAGE,
    filename: 'bg.pdf',
    center: {x: 100, y: 2},
    crop: {x: -1, y: 2.0, w: 10, h: 101},
    offset: {x: 1, y: 4},
    page: 0,
    paperSize: {
        name: 'asdf',
        widthMM: 100,
        heightMM: 200,
    },
    pointA: {x: -1, y: 2},
    pointB: {x: 3, y: 4},
    rotation: 12,
    scaleFactor: 1,
    scaleName: '1:200',
    totalPages: 100,
    uid: 'uid4',
    uri: 'fwkemfewpokfowe',
};
