version: '3.2'

services:
    # Postgres DB instance
    # hostname: db
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=h2x
            - POSTGRES_USER=postgres
        ports:
            - 5432:5432

    # ActiveMQ instance
    # hostname: mq
    mq:
        image: webcenter/activemq
        restart: always
        environment: 
            - ACTIVEMQ_ADMIN_LOGIN=admin
            - ACTIVEMQ_ADMIN_PASSWORD=admin
        ports:
            - 8161:8161
            - 61614:61614 #default WS transport protocol port open

    backend:
        profiles:
            - dev
        build: 
            context: ../node/
            dockerfile: ../docker/dev-backend.Dockerfile
            args:
                - AWS_KEY=${AWS_KEY}
                - AWS_SECRET=${AWS_SECRET}
        image: 'h2x-backend:latest'
        restart: always
        depends_on:
            - db
        ports:
            - 8012:80
        volumes:
            # anonymous volumes to prevent container folders being overwritten by host folders
            - /usr/src/app/node_modules
            - /usr/src/app/backend/node_modules
            - /usr/src/app/backend/dist
            # current code as bind volume
            - ../node/:/usr/src/app/

    frontend:
        profiles:
            - dev
        build:
            context: ../node/
            dockerfile: ../docker/dev-frontend.Dockerfile
        image: 'h2x-frontend:latest'
        restart: always
        ports:
            - 8011:80
        volumes:
            # anonymous volumes to prevent container folders being overwritten by host folders
            - /usr/src/app/node_modules
            - /usr/src/app/frontend/node_modules
            - /usr/src/app/frontend/dist
            # current code as bind volume
            - ../node/:/usr/src/app/

    worker:
        profiles:
            - dev
        build: 
            context: ../node/
            dockerfile: ../docker/dev-worker.Dockerfile
            args:
                - AWS_KEY=${AWS_KEY}
                - AWS_SECRET=${AWS_SECRET}
        image: 'h2x-worker:latest'
        restart: always
        depends_on:
            - db
        ports:
            - 8013:80
        volumes:
            # anonymous volumes to prevent container folders being overwritten by host folders
            - /usr/src/app/node_modules
            - /usr/src/app/backend/node_modules
            - /usr/src/app/backend/dist
            # current code as bind volume
            - ../node/:/usr/src/app/

    prod-web:
        profiles:
            - production
        build:
            context: ../node/
            dockerfile: ../docker/prod-web.Dockerfile
        image: 'h2x-prod-web:latest'
        restart: always
        ports:
            - 80:80
        # volumes:
            # # anonymous volumes to prevent container folders being overwritten by host folders
            # - /usr/src/app/node_modules
            # - /usr/src/app/frontend/node_modules
            # - /usr/src/app/frontend/dist
            # - /usr/src/app/backend/node_modules
            # - /usr/src/app/backend/dist

    prod-worker:
        profiles:
            - production
        build: 
            context: ../node/
            dockerfile: ../docker/prod-worker.Dockerfile
            args:
                - AWS_KEY=${AWS_KEY}
                - AWS_SECRET=${AWS_SECRET}
        image: 'h2x-prod-worker:latest'
        restart: always
        depends_on:
            - db
        ports:
            - 8013:80
        # volumes:
            # # anonymous volumes to prevent container folders being overwritten by host folders
            # - /usr/src/app/node_modules
            # - /usr/src/app/backend/node_modules
            # - /usr/src/app/backend/dist
            # current code as bind volume
            # - ../node/:/usr/src/app/

    backup:
        build:
            context: ../backup/
            dockerfile: Dockerfile
        image: 'h2x-backup:latest'
        environment:
            - PG_S3_BACKUP_BUCKET=h2x-db-backups
            - PG_S3_BACKUP_ACCESS_KEY=${AWS_KEY}
            - PG_S3_BACKUP_SECRET_KEY=${AWS_SECRET}
            - PG_S3_BACKUP_HOST=db
            - PG_S3_BACKUP_USER=postgres
            - PG_S3_BACKUP_DB=h2x
            - PG_S3_BACKUP_PASSWORD=postgres
        restart: always
        depends_on:
            - db

    nginx:
        profiles:
          - dev
        image: 'nginx:latest'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8010:80
        depends_on:
            - backend
            - frontend
