version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pdf-renderer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-420lvuja3pgj"
s3_prefix = "pdf-renderer"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

