version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pdf-renderer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-420lvuja3pgj"
s3_prefix = "pdf-renderer"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"


[stage]
[stage.deploy]
[stage.deploy.parameters]
stack_name = "pdf-renderer-stage"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ojnl9ycp7kvq"
s3_prefix = "pdf-renderer-stage"
region = "us-west-1"
profile = "calin-h2x-testing"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[test]
[test.deploy]
[test.deploy.parameters]
stack_name = "pdf-render-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ojnl9ycp7kvq"
s3_prefix = "pdf-render-test"
region = "us-west-1"
profile = "calin-h2x-testing"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[local]
[local.deploy]
[local.deploy.parameters]
stack_name = "pdf-render-local"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ojnl9ycp7kvq"
s3_prefix = "pdf-render-local"
region = "us-west-1"
profile = "calin-h2x-testing"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
