export enum EntityType {
    BACKGROUND_IMAGE = 'BACKGROUND_IMAGE',
    FLOW_SOURCE = 'FLOW_SOURCE',
    FLOW_RETURN = 'FLOW_RETURN',
    PIPE = 'PIPE',
    VALVE = 'VALVE',
    INVISIBLE_NODE = 'INVISIBLE_NODE',

    TMV = 'TMV',
    COLD_ROUGH_IN = 'COLD_ROUGH_IN',
    HOT_ROUGH_IN = 'HOT_ROUGH_IN',
    WARM_OUT = 'WARM_OUT',

    // Fixtures
    FIXTURE = 'FIXTURE',
}
