export enum EntityType {
    BACKGROUND_IMAGE = 'BACKGROUND_IMAGE',
    FLOW_SOURCE = 'FLOW_SOURCE',
    FLOW_RETURN = 'FLOW_RETURN',
    PIPE = 'PIPE',
    VALVE = 'VALVE',
    INVISIBLE_NODE = 'INVISIBLE_NODE',

    TMV = 'TMV',
    SYSTEM_NODE = 'SYSTEM_NODE',

    // Fixtures
    FIXTURE = 'FIXTURE',
}
